var g_selProvince;
var g_selCity;
var Provinces=new Array(
new Array("北京市","北京市"),
new Array("天津市","天津市"),
new Array("河北省","河北省"),
new Array("山西省","山西省"),
new Array("内蒙古自治区","内蒙古自治区"),
new Array("辽宁省","辽宁省"),
new Array("吉林省","吉林省"),
new Array("黑龙江省","黑龙江省"),
new Array("上海市","上海市"),
new Array("江苏省","江苏省"),
new Array("浙江省","浙江省"),
new Array("安徽省","安徽省"),
new Array("福建省","福建省"),
new Array("江西省","江西省"),
new Array("山东省","山东省"),
new Array("河南省","河南省"),
new Array("湖北省","湖北省"),
new Array("湖南省","湖南省"),
new Array("广东省","广东省"),
new Array("广西壮族自治区","广西壮族自治区"),
new Array("海南省","海南省"),
new Array("重庆市","重庆市"),
new Array("四川省","四川省"),
new Array("贵州省","贵州省"),
new Array("云南省","云南省"),
new Array("西藏自治区","西藏自治区"),
new Array("陕西省","陕西省"),
new Array("甘肃省","甘肃省"),
new Array("青海省","青海省"),
new Array("宁夏回族自治区","宁夏回族自治区"),
new Array("新疆维吾尔自治区","新疆维吾尔自治区"),
new Array("台湾省","台湾省"),
new Array("香港特别行政区","香港特别行政区"),
new Array("澳门特别行政区","澳门特别行政区")
);

var Citys=new Array(
new Array("北京市","北京"),
new Array("天津市","天津"),
new Array("河北省","石家庄"),
new Array("河北省","唐山"),
new Array("河北省","秦皇岛"),
new Array("河北省","张家口"),
new Array("河北省","承德"),
new Array("河北省","廊坊"),
new Array("河北省","邯郸"),
new Array("河北省","邢台"),
new Array("河北省","保定"),
new Array("河北省","沧州"),
new Array("河北省","衡水"),
new Array("山西省","太原"),
new Array("山西省","大同"),
new Array("山西省","阳泉"),
new Array("山西省","晋城"),
new Array("山西省","朔州"),
new Array("山西省","忻州"),
new Array("山西省","离石"),
new Array("山西省","榆次"),
new Array("山西省","临汾"),
new Array("山西省","运城"),
new Array("山西省","长治"),
new Array("内蒙古自治区","呼和浩特"),
new Array("内蒙古自治区","包头"),
new Array("内蒙古自治区","乌海"),
new Array("内蒙古自治区","集宁"),
new Array("内蒙古自治区","东胜"),
new Array("内蒙古自治区","临河"),
new Array("内蒙古自治区","阿拉善左旗"),
new Array("内蒙古自治区","赤峰"),
new Array("内蒙古自治区","通辽"),
new Array("内蒙古自治区","锡林浩特"),
new Array("内蒙古自治区","海拉尔"),
new Array("内蒙古自治区","乌兰浩特"),
new Array("辽宁省","沈阳"),
new Array("辽宁省","大连"),
new Array("辽宁省","鞍山"),
new Array("辽宁省","抚顺"),
new Array("辽宁省","本溪"),
new Array("辽宁省","锦州"),
new Array("辽宁省","营口"),
new Array("辽宁省","阜新"),
new Array("辽宁省","盘锦"),
new Array("辽宁省","铁岭"),
new Array("辽宁省","朝阳"),
new Array("辽宁省","锦西"),
new Array("辽宁省","丹东"),
new Array("吉林省","长春"),
new Array("吉林省","吉林"),
new Array("吉林省","四平"),
new Array("吉林省","辽源"),
new Array("吉林省","浑江"),
new Array("吉林省","白城"),
new Array("吉林省","延吉"),
new Array("吉林省","通化"),
new Array("黑龙江省","哈尔滨"),
new Array("黑龙江省","鸡西"),
new Array("黑龙江省","鹤岗"),
new Array("黑龙江省","双鸭山"),
new Array("黑龙江省","伊春"),
new Array("黑龙江省","佳木斯"),
new Array("黑龙江省","七台河"),
new Array("黑龙江省","牡丹江"),
new Array("黑龙江省","绥化"),
new Array("黑龙江省","齐齐哈尔"),
new Array("黑龙江省","大庆"),
new Array("黑龙江省","黑河"),
new Array("黑龙江省","加格达奇"),
new Array("上海市","上海"),
new Array("江苏省","南京"),
new Array("江苏省","无锡"),
new Array("江苏省","徐州"),
new Array("江苏省","常州"),
new Array("江苏省","苏州"),
new Array("江苏省","南通"),
new Array("江苏省","连云港"),
new Array("江苏省","淮阴"),
new Array("江苏省","盐城"),
new Array("江苏省","扬州"),
new Array("江苏省","镇江"),
new Array("浙江省","杭州"),
new Array("浙江省","宁波"),
new Array("浙江省","温州"),
new Array("浙江省","嘉兴"),
new Array("浙江省","湖州"),
new Array("浙江省","绍兴"),
new Array("浙江省","金华"),
new Array("浙江省","衢州"),
new Array("浙江省","舟山"),
new Array("浙江省","丽水"),
new Array("浙江省","临海"),
new Array("安徽省","合肥"),
new Array("安徽省","芜湖"),
new Array("安徽省","蚌埠"),
new Array("安徽省","淮南"),
new Array("安徽省","马鞍山"),
new Array("安徽省","淮北"),
new Array("安徽省","铜陵"),
new Array("安徽省","安庆"),
new Array("安徽省","黄山"),
new Array("安徽省","阜阳"),
new Array("安徽省","宿州"),
new Array("安徽省","滁州"),
new Array("安徽省","六安"),
new Array("安徽省","宣州"),
new Array("安徽省","巢湖"),
new Array("安徽省","贵池"),
new Array("福建省","福州"),
new Array("福建省","厦门"),
new Array("福建省","莆田"),
new Array("福建省","三明"),
new Array("福建省","泉州"),
new Array("福建省","漳州"),
new Array("福建省","南平"),
new Array("福建省","宁德"),
new Array("福建省","龙岩"),
new Array("江西省","南昌"),
new Array("江西省","景德镇"),
new Array("江西省","赣州"),
new Array("江西省","萍乡"),
new Array("江西省","九江"),
new Array("江西省","新余"),
new Array("江西省","鹰潭"),
new Array("江西省","宜春"),
new Array("江西省","上饶"),
new Array("江西省","吉安"),
new Array("江西省","临川"),
new Array("山东省","济南"),
new Array("山东省","青岛"),
new Array("山东省","淄博"),
new Array("山东省","枣庄"),
new Array("山东省","东营"),
new Array("山东省","烟台"),
new Array("山东省","潍坊"),
new Array("山东省","济宁"),
new Array("山东省","泰安"),
new Array("山东省","威海"),
new Array("山东省","日照"),
new Array("山东省","滨州"),
new Array("山东省","德州"),
new Array("山东省","聊城"),
new Array("山东省","临沂"),
new Array("山东省","菏泽"),
new Array("河南省","郑州"),
new Array("河南省","开封"),
new Array("河南省","洛阳"),
new Array("河南省","平顶山"),
new Array("河南省","安阳"),
new Array("河南省","鹤壁"),
new Array("河南省","新乡"),
new Array("河南省","焦作"),
new Array("河南省","濮阳"),
new Array("河南省","许昌"),
new Array("河南省","漯河"),
new Array("河南省","三门峡"),
new Array("河南省","商丘"),
new Array("河南省","周口"),
new Array("河南省","驻马店"),
new Array("河南省","南阳"),
new Array("河南省","信阳"),
new Array("湖北省","武汉"),
new Array("湖北省","黄石"),
new Array("湖北省","十堰"),
new Array("湖北省","沙市"),
new Array("湖北省","宜昌"),
new Array("湖北省","襄樊"),
new Array("湖北省","鄂州"),
new Array("湖北省","荆门"),
new Array("湖北省","黄州"),
new Array("湖北省","孝感"),
new Array("湖北省","咸宁"),
new Array("湖北省","江陵"),
new Array("湖北省","恩施"),
new Array("湖南省","长沙"),
new Array("湖南省","衡阳"),
new Array("湖南省","邵阳"),
new Array("湖南省","郴州"),
new Array("湖南省","永州"),
new Array("湖南省","大庸"),
new Array("湖南省","怀化"),
new Array("湖南省","吉首"),
new Array("湖南省","株洲"),
new Array("湖南省","湘潭"),
new Array("湖南省","岳阳"),
new Array("湖南省","常德"),
new Array("湖南省","益阳"),
new Array("湖南省","娄底"),
new Array("广东省","广州"),
new Array("广东省","深圳"),
new Array("广东省","汕尾"),
new Array("广东省","惠州"),
new Array("广东省","河源"),
new Array("广东省","佛山"),
new Array("广东省","清远"),
new Array("广东省","东莞"),
new Array("广东省","珠海"),
new Array("广东省","江门"),
new Array("广东省","肇庆"),
new Array("广东省","中山"),
new Array("广东省","湛江"),
new Array("广东省","茂名"),
new Array("广东省","韶关"),
new Array("广东省","汕头"),
new Array("广东省","梅州"),
new Array("广东省","阳江"),
new Array("广西壮族自治区","南宁"),
new Array("广西壮族自治区","梧州"),
new Array("广西壮族自治区","玉林"),
new Array("广西壮族自治区","桂林"),
new Array("广西壮族自治区","百色"),
new Array("广西壮族自治区","河池"),
new Array("广西壮族自治区","钦州"),
new Array("广西壮族自治区","柳州"),
new Array("广西壮族自治区","北海"),
new Array("海南省","海口"),
new Array("海南省","三亚"),
new Array("四川省","成都"),
new Array("四川省","康定"),
new Array("四川省","雅安"),
new Array("四川省","马尔康"),
new Array("四川省","自贡"),
new Array("重庆市","重庆"),
new Array("四川省","南充"),
new Array("四川省","泸州"),
new Array("四川省","德阳"),
new Array("四川省","绵阳"),
new Array("四川省","遂宁"),
new Array("四川省","内江"),
new Array("四川省","乐山"),
new Array("四川省","宜宾"),
new Array("四川省","广元"),
new Array("四川省","达县"),
new Array("四川省","西昌"),
new Array("四川省","攀枝花"),
new Array("重庆省","黔江土家族苗族自治县"),
new Array("贵州省","贵阳"),
new Array("贵州省","六盘水"),
new Array("贵州省","铜仁"),
new Array("贵州省","安顺"),
new Array("贵州省","凯里"),
new Array("贵州省","都匀"),
new Array("贵州省","兴义"),
new Array("贵州省","毕节"),
new Array("贵州省","遵义"),
new Array("云南省","昆明"),
new Array("云南省","东川"),
new Array("云南省","曲靖"),
new Array("云南省","楚雄"),
new Array("云南省","玉溪"),
new Array("云南省","个旧"),
new Array("云南省","文山"),
new Array("云南省","思茅"),
new Array("云南省","昭通"),
new Array("云南省","景洪"),
new Array("云南省","大理"),
new Array("云南省","保山"),
new Array("云南省","潞西"),
new Array("云南省","丽江纳西族自治县"),
new Array("云南省","泸水"),
new Array("云南省","中甸"),
new Array("云南省","临沧"),
new Array("西藏自治区","拉萨"),
new Array("西藏自治区","昌都"),
new Array("西藏自治区","乃东"),
new Array("西藏自治区","日喀则"),
new Array("西藏自治区","那曲"),
new Array("西藏自治区","噶尔"),
new Array("西藏自治区","林芝"),
new Array("陕西省","西安"),
new Array("陕西省","铜川"),
new Array("陕西省","宝鸡"),
new Array("陕西省","咸阳"),
new Array("陕西省","渭南"),
new Array("陕西省","汉中"),
new Array("陕西省","安康"),
new Array("陕西省","商州"),
new Array("陕西省","延安"),
new Array("陕西省","榆林"),
new Array("甘肃省","兰州"),
new Array("甘肃省","白银"),
new Array("甘肃省","金昌"),
new Array("甘肃省","天水"),
new Array("甘肃省","张掖"),
new Array("甘肃省","武威"),
new Array("甘肃省","定西"),
new Array("甘肃省","成县"),
new Array("甘肃省","平凉"),
new Array("甘肃省","西峰"),
new Array("甘肃省","临夏"),
new Array("甘肃省","夏河"),
new Array("甘肃省","嘉峪关"),
new Array("甘肃省","酒泉"),
new Array("青海省","西宁"),
new Array("青海省","平安"),
new Array("青海省","门源回族自治县"),
new Array("青海省","同仁"),
new Array("青海省","共和"),
new Array("青海省","玛沁"),
new Array("青海省","玉树"),
new Array("青海省","德令哈"),
new Array("宁夏回族自治区","银川"),
new Array("宁夏回族自治区","石嘴山"),
new Array("宁夏回族自治区","吴忠"),
new Array("宁夏回族自治区","固原"),
new Array("新疆维吾尔自治区","乌鲁木齐"),
new Array("新疆维吾尔自治区","克拉玛依"),
new Array("新疆维吾尔自治区","吐鲁番"),
new Array("新疆维吾尔自治区","哈密"),
new Array("新疆维吾尔自治区","昌吉"),
new Array("新疆维吾尔自治区","博乐"),
new Array("新疆维吾尔自治区","库尔勒"),
new Array("新疆维吾尔自治区","阿克苏"),
new Array("新疆维吾尔自治区","阿图什"),
new Array("新疆维吾尔自治区","喀什"),
new Array("新疆维吾尔自治区","伊宁"),
new Array("台湾省","台北"),
new Array("台湾省","基隆"),
new Array("台湾省","台南"),
new Array("台湾省","高雄"),
new Array("台湾省","台中"),
new Array("辽宁省","辽阳"),
new Array("新疆维吾尔自治区","和田"),
new Array("西藏自治区","泽当镇"),
new Array("西藏自治区","八一镇"),
new Array("澳门特别行政区","澳门"),
new Array("香港特别行政区","香港")
);

function FillProvinces(selProvince)
{
    selProvince.options[0]=new Option("请选择","请选择");
    for(i=0;i<Provinces.length;i++)
    {
        selProvince.options[i+1]=new Option(Provinces[i][1],Provinces[i][1]);
    }
    selProvince.options[0].selected=true;
    selProvince.length=i+1;
}

function FillCitys(selCity,ProvinceCode)
{
    //if the province is a direct-managed city, like Beijing, shanghai, tianjin, chongqin,hongkong, macro
        //need not "请选择选项"
        if(ProvinceCode=="北京市"||ProvinceCode=="天津市"||ProvinceCode=="上海市"
                 ||ProvinceCode=="香港特别行政区"||ProvinceCode=="澳门特别行政区"||ProvinceCode=="重庆市")
             count=0;
        else
                {selCity.options[0]=new Option("请选择",ProvinceCode);
                count=1;}
    for(i=0;i<Citys.length;i++)
    {
        if(Citys[i][0].toString()==ProvinceCode)
        {
            selCity.options[count]=new Option(Citys[i][1],Citys[i][1]);
            count=count+1;
        }
    }
    selCity.options[0].selected=true;
    selCity.length=count;
}

function Province_onchange()
{
    FillCitys(g_selCity,g_selProvince.value);
}

function InitCitySelect(selProvince,selCity)
{
    //alert("begin");
    g_selProvince=selProvince;
    g_selCity=selCity;
    selProvince.onchange=Function("Province_onchange();");
    FillProvinces(selProvince);
    Province_onchange();
}

function InitCitySelect2(selProvince,selCity,CityCode)
{
    InitCitySelect(selProvince,selCity)
    for(i=0;i<selProvince.length;i++)
    {
        if(selProvince.options[i].value.substring(0,2)==CityCode.substring(0,2))
        {
            selProvince.options[i].selected=true;
        }
    }
    Province_onchange();
    for(i=0;i<selCity.length;i++)
    {
        if(selCity.options[i].value==CityCode)
        {
            selCity.options[i].selected=true;
        }
    }
}